after-startup-command = ['exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0']

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 15
    inner.vertical =   15
    outer.left =       15
    outer.bottom =     15
    outer.top =        15
    outer.right =      15

[mode.main.binding]
    
    # open terminal
    #alt-enter = '''exec-and-forget osascript -e '
    #tell application "Terminal"
    #     do script
    #     activate
    #end tell'
    #'''

    # Toggle Spotify Pause
    cmd-shift-p = '''exec-and-forget osascript -e '
        tell application "Spotify"
        playpause
    end tell'
    '''

    # open common apps
    cmd-t = "exec-and-forget open -a /Applications/Alacritty.app"
    cmd-b = "exec-and-forget open -a /Applications/Arc.app"
    cmd-s = "exec-and-forget open -a /Applications/Slack.app"
    cmd-m = "exec-and-forget open -a 'Messages'"
    cmd-a = "exec-and-forget open -a /Applications/ChatGPT.app"
    cmd-f = "exec-and-forget open -a 'Finder'"

    # cmd-slash = 'layout tiles horizontal vertical'
    # cmd-comma = 'layout accordion horizontal vertical'

    cmd-left = 'focus left'
    cmd-down = 'focus down'
    cmd-up = 'focus up'
    cmd-right = 'focus right'
    cmd-w = 'close'

    cmd-shift-left = 'move left'
    cmd-shift-down = 'move down'
    cmd-shift-up = 'move up'
    cmd-shift-right = 'move right'

    cmd-minus = 'resize smart -50'
    cmd-equal = 'resize smart +50'

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'

    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    
    ctrl-left  = 'workspace prev'
    ctrl-right = 'workspace next'
    #alt-tab = 'workspace-back-and-forth'
    #alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    cmd-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    cmd-shift-h = ['join-with left', 'mode main']
    cmd-shift-j = ['join-with down', 'mode main']
    cmd-shift-k = ['join-with up', 'mode main']
    cmd-shift-l = ['join-with right', 'mode main']

    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']
